### PR TITLE
Update Ledger Nano Device IDs (So it works with Ledger RVN app 1.5.1+)

### PR DESCRIPTION
**Pull request by 3rdIteration**
See
https://www.ledger.com/windows-10-update-sunsetting-u2f-tunnel-transport-for-ledger-devices/

### CODE REVIEW

**Comment by josefbaltz** [comment]
Bump, this needs to be added to fix the damn wallet, why does this not have an active maintainer ...

**Comment by Synicide** [comment]
> Bump, this needs to be added to fix the damn wallet, why does this not have an active maintainer ...

The ledger.py file changed here can be edited directly without compiling or reinstalling the wallet.  This worked for me on a nanoS.

**Review by Synicide — APPROVED** [review]
working for nanoS

**Comment by TronBlack** [comment]
Would you add your pull request here?
https://github.com/RavencoinFoundation/electrum-raven

If not, I'll make the same changes in a few days.  The fork did not carry over the PR.

**Comment by 3rdIteration** [comment]
> Would you add your pull request here?
> https://github.com/RavencoinFoundation/electrum-raven
> 
> If not, I'll make the same changes in a few days. The fork did not carry over the PR.

Done

**Comment by mknippen** [comment]
+1

**Comment by radvansky-tomas** [comment]
Cannot install on ledgerX on OSX
```
No hardware device detected.
To trigger a rescan, press 'Next'.

On Linux, you might have to add a new permission to your udev rules.


Debug message
  No exceptions encountered.
```

**Comment by FibreFoX** [comment]
Is there any reason that this does not get merged? The travisCI build just shows a broken CI-setup, but not by this PR.

**Comment by Rcmining** [comment]
I solved this issue by mean to use this rvn-electrum wallet built with this binaries file of here
https://twitter.com/RC_Mining/status/1363298738723295232?s=20
https://github.com/RainbowMiner/miner-binaries/releases/tag/v3.3.8-rvn3-fixed

**Comment by mcflythekid** [comment]
@standard-error Where the hell are you

**Review by abhisaha1 — APPROVED** [review]

**Pull request closed without merging**
